name: Test OSQP Matlab Interface

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Build OSQP interface
        uses: matlab-actions/run-command@v1
        with:
          command: make_osqp

      - name: Run tests
        uses: matlab-actions/run-tests@v1
        with:
          source-folder: ./
          select-by-folder: unittests
          test-results-junit: test-results/results.xml

      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v2
        with:
          check_name: Linux test results
          report_paths: 'test-results/**/*.xml'
