name: Release 

on:
  push:
    tags:
      - '*'

jobs:
  build:
    # As of August 30, 2021 Matlab isn't able to be used on Windows or macOS on GitHub shared runners
    # (it errors saying the dependencies aren't available on those platforms). Instead we can only
    # test on ubuntu-latest. The matrix below is preserved here in case Matlab support is added
    # to those other platforms.
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [ubuntu-latest, macos-latest, windows-latest]

#    runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest

    steps:

      - name: Setup Envvars
        run: |
          echo "OSQP_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Generate binary
        uses: matlab-actions/run-command@v1
        with:
          command: cd package, package_osqp('${{env.OSQP_VERSION}}')

      - name: Release binary
        uses: softprops/action-gh-release@v1
        with:
          files: package/osqp-matlab-linux64.tar.gz
